WebApplicationBook2/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebApplicationBook2.Models;

namespace WebApplicationBook2.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart _cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            _cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

WebApplicationBook2/Components/NavigationMenuViewComponent.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WebApplicationBook2.Models;

namespace WebApplicationBook2.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private readonly IProductRepository _repository;

        public NavigationMenuViewComponent(IProductRepository repository)
        {
            _repository = repository;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(_repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

WebApplicationBook2/Controllers/CartController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WebApplicationBook2.Infrastructure;
using WebApplicationBook2.Models;
using WebApplicationBook2.Models.ViewModels;

namespace WebApplicationBook2.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductRepository _repository;
        private readonly Cart _cart;
        
        public CartController(IProductRepository repository, Cart cartService)
        {
            _repository = repository;
            _cart = cartService;
        }

        [Route("Cart/Index")]
        public ViewResult Index(string returnUrl) => 
            View(new CartIndexViewModel 
            {
                Cart = _cart,
                ReturnUrl = returnUrl
            });

        [Route("Cart/AddToCart")]
        public RedirectToActionResult AddToCart(int productId, string returnUrl)
        {
            var product = _repository.Products
                .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                _cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new {returnUrl});
        }

        [Route("Cart/RemoveFromCart")]
        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl)
        {
            var product = _repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                _cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new {returnUrl});
        }
    }
}

WebApplicationBook2/Views/Shared/ProductSummary.cshtml
@model Product

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-light p-1">
        <h4>
            @Model.Name
            <span class="badge badge-pill badge-primary">
                <small>@Model.Price.ToString("C")</small>
            </span>
        </h4>
    </div>
    <form id="@Model.ProductID" 
          asp-controller="Cart" 
          asp-action="AddToCart"
          method="get">
        <input type="hidden" asp-for="ProductID" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text р-1">
            @Model.Description
            <button type="submit"
                    class="btn btn-success btn-sm float-right">
                Add То Cart
            </button>
        </span>
    </form>
</div>

WebApplicationBook2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" 
          asp-href-include="/lib/bootstrap/dist/**/*.min.css"
          asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <link media="all" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<div class="navbar navbar-dark bg-dark" role="navigation">
    <div class="row">
        <a class="navbar-brand" href="#">SPORTS STORE</a>
        <div class="col-4 text-right">
            @await Component.InvokeAsync("CartSummary");
        </div>
    </div>
</div>
<div class="row m-1 p-1">
    <div id="categories" class="col-3">
        @await Component.InvokeAsync("NavigationMenu")
    </div>
    <div class="col-9">
        @RenderBody()
    </div>
</div>
</body>
</html>